# Generated by Django 3.2.16 on 2022-10-27 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221027_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='team_consult',
        ),
        migrations.AddField(
            model_name='account',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.team'),
        ),
    ]
